version: '3.8'

services:
  uninove-future-system:
    container_name: uninove-future-system
    build:
      dockerfile: Dockerfile
    working_dir: /uninove-future-system
    volumes:
      - ./:/uninove-future-system
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container_uninove_system:5432/escolares"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=changeme"
    command: mvn clean install spring-boot:run

  postgres:
    container_name: postgres_container_uninove_system
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: escolares
    ports:
      - "5432:5432"
    restart: unless-stopped
